# Docker Compose Configuration
# Defines services, networks, and volumes for the Counterspell Event Client.

services:
  event-website:
    build: .
    container_name: event_website
    working_dir: /usr/src/app
    ports:
      - "4173:4173"
    command: ["npm", "start"]
    networks:
      - app-network

networks:
  app-network:
    external: true
