services:
  event-website:
    build: .
    container_name: event_website
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
